### PR TITLE
update to 3.81 for example of custom game Property

### PR DESCRIPTION
**Pull request by beelee1**
trying to add this to POS2 for @ron-murhammer to look at

### CODE REVIEW

**Comment by beelee1** [comment]
not sure if it worked

**Comment by beelee1** [comment]
so I f this gets to you, I mentioned on the triplea site that if the wording was deemed inappropriate it could be changed to "Conscription". Didn't really think about it, but I guess some might think so.

**Comment by ron-murhammer** [comment]
@beelee1 So I'm fine adding an example of a customer property here but I'd prefer to avoid controversial terms.

**Comment by beelee1** [comment]
yea idk if you got the message about changing it to "Conscription". Didn't occur to me while I was doing it. I'll change the wording and try another PR. i'm still not quite sure how it works on anothers repo

**Pull request closed without merging**
